### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by adambaumeister** [cdot65/pan-os-upgrade#15]
Code should support semantic versioning based on conventional commits to simplify the release cycle.

**Comment by cdot65** [comment]
Hey Adam, I have built this project out with poetry, which implemented a semantic versioning scheme to the project. I'm currently working on #16 and this request will be the foundation of our versioning for PyPi

**Comment by cdot65** [comment]
Semantic versioning has been enforced through Poetry, closing out this alongside #16
