### ISSUE TITLE
UnicodeEncodeError on Windows When Logging Messages with Emojis

### ISSUE THREAD

**Issue by cdot65** [cdot65/pan-os-upgrade#28]
## Environment

- OS: Windows 10
- Python Version: 3.12
- Application: `pan-os-upgrade`

## Issue Summary

When running the `pan-os-upgrade` script on Windows machines, a `UnicodeEncodeError` is thrown during logging operations that involve emojis. This issue seems to stem from the default character encoding in Windows command prompt and PowerShell, which does not support certain Unicode characters used in the script's logging messages.

## Steps to Reproduce

1. Run the `pan-os-upgrade` script using PowerShell or cmd.exe on a Windows machine.
2. Observe the `UnicodeEncodeError` that occurs when the script attempts to log messages containing emojis.

## Expected Behavior

The script should log messages without causing encoding errors, regardless of the operating system or the shell used.

## Actual Behavior

The script fails to log messages correctly and throws a `UnicodeEncodeError` when it encounters emojis in log messages on Windows.

## Possible Solutions

- Remove emojis from log messages to ensure compatibility across different platforms.
- Implement a custom logging handler or filter to encode log messages in UTF-8 and handle encoding issues.

## Additional Context

This issue impacts Windows users of the `pan-os-upgrade` tool, potentially affecting usability and user experience. Addressing this issue would improve the tool's robustness and cross-platform compatibility.

**Comment by cdot65** [comment]
The inclusion of a Docker image provides us with some time to sort this out.

**Comment by adambaumeister** [comment]
This should have been fixed in #45 through the inclusion of a specific encoding (utf-8) in the logging handler. Unsure why the default doesn't work on windows.

**Comment by cdot65** [comment]
Confirmed this issue has been resolved.
